In [2]:
import sys
sys.path.append("../")

import pandas as pd
from murasame.utils import make_board, append_seat_number, trim_board

# 名簿の読み込み

In [2]:
data = pd.read_excel("members.xlsx", index_col=0)
print(data)

        名前          読み        学校   地域
No
1   多田 のぞみ      ただ のぞみ     北海道大学  NaN
2    吉田 明伸    よしだ あきのぶ     北海道大学  NaN
3     長野 努     ながの つとむ      東北大学  NaN
4     谷口 慈    たにぐち めぐみ      東北大学  NaN
5   二宮 佳那子    にのみや かなこ      東北大学  NaN
6   武田 絵理佳     たけだ えりか      東北大学  NaN
7    渡邉 竜平  わたなべ りゅうへい      東北大学  NaN
8     澤 亮介    さわ りょうすけ      東北大学  NaN
9    中島 真幸   なかじま まさゆき      東北大学  NaN
10    横山 玲    よこやま あきら      東北大学  NaN
11  石田 孝一郎  いしだ こういちろう      東北大学  NaN
12   関口 真澄    せきぐち ますみ      筑波大学  NaN
13   栗田 京香    くりた きょうか      筑波大学  NaN
14   大谷 広之   おおたに ひろゆき      筑波大学  NaN
15   大谷 光紗     おおたに みさ      筑波大学  NaN
16  川嶋 小夜子    かわしま さよこ     富士崎高校  NaN
17  中曽根 智歌     なかそね ちか     富士崎高校  NaN
18   中島 千春    なかしま ちはる     富士崎高校  NaN
19   根来 夏実     ねごろ なつみ     富士崎高校  NaN
20  坂野 有紀子     ばんの ゆきこ     富士崎高校  NaN
21   増田 有以      ますだ ゆい     富士崎高校  NaN
22   入江 貴紀    いりえ たかのり      北央学園  NaN
23   崎山 圭佑   さきやま けいすけ      北央学園  NaN
24   滝沢 信之   たきざわ のぶゆき      北央学園  NaN
25   村川 英雄    むらかわ ひでお      北央学園  NaN
26   川嵜 陽介   かわさき ようすけ      北央学園  NaN
27   畑中 妙美    はたなか たえみ  お茶の水女子大学  NaN
28  相澤 里恵子    あいざわ りえこ  お茶の水女子大学  NaN
29   青山 秀美    あおやま ひでみ    青山学院大学  NaN
30   長澤 洋司    ながさわ ようじ    青山学院大学  NaN
..     ...         ...       ...  ...
63  曽我部 大志     そがべ たいし      静岡大学  NaN
64   今津 るり      いまづ るり      静岡大学  NaN
65   江島 宣子     えじま のりこ      静岡大学  NaN
66   松坂 智尋    まつざか ちひろ      京都大学    西
67   仲川 真美    なかがわ まなみ      京都大学    西
68  阿久津 千保      あくつ ちほ      京都大学    西
69   瀬尾 英史     せお ひでふみ      京都大学    西
70   押川 雄貴    おしかわ ゆうき      京都大学    西
71   當山 雅英   とうやま まさひで      京都大学    西
72  大串 万由美    おおぐし まゆみ      大阪大学    西
73   宮里 桃子    みやざと とうこ      大阪大学    西
74   木曽 史也      きそ ふみや      大阪大学    西
75   神野 勇作    かみの ゆうさく      大阪大学    西
76   水木 光美     みずき てるみ      大阪大学    西
77   松林 杏南   まつばやし あんな      大阪大学    西
78   塩原 清彦   しおばら きよひこ     立命館大学    西
79  丸尾 里栄子     まるお りえこ     立命館大学    西
80   苅谷 克美     かりや かつみ     立命館大学    西
81   江副 可織     えぞえ かおり     立命館大学    西
82   南川 礼美   みなみかわ あやみ     立命館大学    西
83  梅崎 千穂美    うめざき ちほみ      神戸大学    西
84   渋谷 冬華    しぶたに ふゆか      神戸大学    西
85  茨木 百合江    いばらき ゆりえ      神戸大学    西
86  権藤 沙江子    ごんどう さえこ      神戸大学    西
87    笹 聖佳      ささ せいか      神戸大学    西
88   長浜 小波    ながはま こなみ      神戸大学    西
89  安村 友理佳    やすむら ゆりか      九州大学    西
90  長門 奈美枝     ながと なみえ      九州大学    西
91  早乙女 安世    さおとめ やすよ      九州大学    西
92  漆原 ありか   うるしばら ありか      九州大学    西

[92 rows x 4 columns]

# 対戦を組む

- `keys`に指定した要素が重複する人同士は当たらないように対戦を組む
    - アルゴリズムは競技会規定に書かれている方法に律儀に従っている
- 今回は**学校**と**地域**が重複しないようになっている。
- 西同士は当てたくないが東同士は当てても良い場合、「東」と入力するのではなく空欄にしておけばよい
    - 表の中で`NaN`と書かれているのはもともと空欄だったセル

## アルゴリズム    
1. ランダムに1人を選ぶ
2. 次に置くのが奇数番目
    - そのまま置く
3. 次に置くのが偶数番目
    - 対戦に問題がなければそのまま置く
4. 対戦に問題がある場合(同会など)
    - 最後の試合でなければ次の奇数番目に置く
5. 最後の試合の場合
    - 最初の人から順番に、場所を交換しても問題ない人を探して入れ替える

In [3]:
board = make_board(data, keys=["学校", "地域"])
board.to_excel("board.xlsx")
print(board.as_dataframe(trim=True))

         名前          読み        学校   地域
1     関戸 和幸    せきど かずゆき     早稲田大学  NaN
2    早乙女 安世    さおとめ やすよ      九州大学    西
3     畑中 妙美    はたなか たえみ  お茶の水女子大学  NaN
4     今津 るり      いまづ るり      静岡大学  NaN
5     藤岡 万由     ふじおか まゆ      明治大学  NaN
6    中曽根 智歌     なかそね ちか     富士崎高校  NaN
7    武田 絵理佳     たけだ えりか      東北大学  NaN
8     神野 勇作    かみの ゆうさく      大阪大学    西
9     栗田 京香    くりた きょうか      筑波大学  NaN
10    國枝 文江    くにえだ ふみえ     國學院大學  NaN
11    中島 千春    なかしま ちはる     富士崎高校  NaN
12    大谷 光紗     おおたに みさ      筑波大学  NaN
13    宮里 桃子    みやざと とうこ      大阪大学    西
14    三井 眞里      みつい まり      法政大学  NaN
15   大串 万由美    おおぐし まゆみ      大阪大学    西
16    崎山 圭佑   さきやま けいすけ      北央学園  NaN
17    仲川 真美    なかがわ まなみ      京都大学    西
18    吉田 明伸    よしだ あきのぶ     北海道大学  NaN
19    日向 正義    ひなた まさよし      法政大学  NaN
20   安村 友理佳    やすむら ゆりか      九州大学    西
21    篠崎 洋明   しのざき ひろあき      中央大学  NaN
22    塩原 清彦   しおばら きよひこ     立命館大学    西
23    諸岡 一成   もろおか かずなり     早稲田大学  NaN
24   梅崎 千穂美    うめざき ちほみ      神戸大学    西
25    植村 麗加    うえむら れいか    慶応義塾大学  NaN
26    高畑 なみ     たかはた なみ      東京大学  NaN
27   曽我部 大志     そがべ たいし      静岡大学  NaN
28     笹 聖佳      ささ せいか      神戸大学    西
29   阿久津 千保      あくつ ちほ      京都大学    西
30    滝沢 信之   たきざわ のぶゆき      北央学園  NaN
31    木曽 史也      きそ ふみや      大阪大学    西
32    根岸 基樹     ねぎし もとき     早稲田大学  NaN
33    水木 光美     みずき てるみ      大阪大学    西
34   二宮 佳那子    にのみや かなこ      東北大学  NaN
35   漆原 ありか   うるしばら ありか      九州大学    西
36    江島 宣子     えじま のりこ      静岡大学  NaN
37    苅谷 克美     かりや かつみ     立命館大学    西
38    濱本 瑠菜     はまもと るな      東京大学  NaN
39    渡邉 竜平  わたなべ りゅうへい      東北大学  NaN
40    濱口 千花     はまぐち ちか     早稲田大学  NaN
41    川嵜 陽介   かわさき ようすけ      北央学園  NaN
42   柳澤 久里子   やなぎさわ くりこ      法政大学  NaN
43   平賀 舞衣子     ひらが まいこ      法政大学  NaN
44    福永 新子    ふくなが しんこ      東京大学  NaN
45    南川 礼美   みなみかわ あやみ     立命館大学    西
46    大崎 貴信   おおさき たかのぶ    慶応義塾大学  NaN
47     谷 成江      たに まさえ      中央大学  NaN
48    関口 真澄    せきぐち ますみ      筑波大学  NaN
49  八木橋 のどか    やぎはし のどか      明治大学  NaN
50    小阪 俊一   こさか しゅんいち      東京大学  NaN
51    寺西 加苗    てらにし かなえ      法政大学  NaN
52    村川 英雄    むらかわ ひでお      北央学園  NaN
53    大谷 広之   おおたに ひろゆき      筑波大学  NaN
54    根来 夏実     ねごろ なつみ     富士崎高校  NaN
55   本間 真己子     ほんま まきこ     早稲田大学  NaN
56    落合 千明    おちあい ちあき      東京大学  NaN

# 名簿の出力

座席番号を付加して出力

In [4]:
sheet = append_seat_number(data, board, "座席", "不戦")
sheet.to_excel("list.xlsx")
print(sheet)

        名前          読み        学校   地域  座席
No
1   多田 のぞみ      ただ のぞみ     北海道大学  NaN  不戦
2    吉田 明伸    よしだ あきのぶ     北海道大学  NaN  18
3     長野 努     ながの つとむ      東北大学  NaN  不戦
4     谷口 慈    たにぐち めぐみ      東北大学  NaN  不戦
5   二宮 佳那子    にのみや かなこ      東北大学  NaN  34
6   武田 絵理佳     たけだ えりか      東北大学  NaN   7
7    渡邉 竜平  わたなべ りゅうへい      東北大学  NaN  39
8     澤 亮介    さわ りょうすけ      東北大学  NaN  不戦
9    中島 真幸   なかじま まさゆき      東北大学  NaN  不戦
10    横山 玲    よこやま あきら      東北大学  NaN  不戦
11  石田 孝一郎  いしだ こういちろう      東北大学  NaN  不戦
12   関口 真澄    せきぐち ますみ      筑波大学  NaN  48
13   栗田 京香    くりた きょうか      筑波大学  NaN   9
14   大谷 広之   おおたに ひろゆき      筑波大学  NaN  53
15   大谷 光紗     おおたに みさ      筑波大学  NaN  12
16  川嶋 小夜子    かわしま さよこ     富士崎高校  NaN  不戦
17  中曽根 智歌     なかそね ちか     富士崎高校  NaN   6
18   中島 千春    なかしま ちはる     富士崎高校  NaN  11
19   根来 夏実     ねごろ なつみ     富士崎高校  NaN  54
20  坂野 有紀子     ばんの ゆきこ     富士崎高校  NaN  不戦
21   増田 有以      ますだ ゆい     富士崎高校  NaN  不戦
22   入江 貴紀    いりえ たかのり      北央学園  NaN  不戦
23   崎山 圭佑   さきやま けいすけ      北央学園  NaN  16
24   滝沢 信之   たきざわ のぶゆき      北央学園  NaN  30
25   村川 英雄    むらかわ ひでお      北央学園  NaN  52
26   川嵜 陽介   かわさき ようすけ      北央学園  NaN  41
27   畑中 妙美    はたなか たえみ  お茶の水女子大学  NaN   3
28  相澤 里恵子    あいざわ りえこ  お茶の水女子大学  NaN  不戦
29   青山 秀美    あおやま ひでみ    青山学院大学  NaN  不戦
30   長澤 洋司    ながさわ ようじ    青山学院大学  NaN  不戦
..     ...         ...       ...  ...  ..
63  曽我部 大志     そがべ たいし      静岡大学  NaN  27
64   今津 るり      いまづ るり      静岡大学  NaN   4
65   江島 宣子     えじま のりこ      静岡大学  NaN  36
66   松坂 智尋    まつざか ちひろ      京都大学    西  不戦
67   仲川 真美    なかがわ まなみ      京都大学    西  17
68  阿久津 千保      あくつ ちほ      京都大学    西  29
69   瀬尾 英史     せお ひでふみ      京都大学    西  不戦
70   押川 雄貴    おしかわ ゆうき      京都大学    西  不戦
71   當山 雅英   とうやま まさひで      京都大学    西  不戦
72  大串 万由美    おおぐし まゆみ      大阪大学    西  15
73   宮里 桃子    みやざと とうこ      大阪大学    西  13
74   木曽 史也      きそ ふみや      大阪大学    西  31
75   神野 勇作    かみの ゆうさく      大阪大学    西   8
76   水木 光美     みずき てるみ      大阪大学    西  33
77   松林 杏南   まつばやし あんな      大阪大学    西  不戦
78   塩原 清彦   しおばら きよひこ     立命館大学    西  22
79  丸尾 里栄子     まるお りえこ     立命館大学    西  不戦
80   苅谷 克美     かりや かつみ     立命館大学    西  37
81   江副 可織     えぞえ かおり     立命館大学    西  不戦
82   南川 礼美   みなみかわ あやみ     立命館大学    西  45
83  梅崎 千穂美    うめざき ちほみ      神戸大学    西  24
84   渋谷 冬華    しぶたに ふゆか      神戸大学    西  不戦
85  茨木 百合江    いばらき ゆりえ      神戸大学    西  不戦
86  権藤 沙江子    ごんどう さえこ      神戸大学    西  不戦
87    笹 聖佳      ささ せいか      神戸大学    西  28
88   長浜 小波    ながはま こなみ      神戸大学    西  不戦
89  安村 友理佳    やすむら ゆりか      九州大学    西  20
90  長門 奈美枝     ながと なみえ      九州大学    西  不戦
91  早乙女 安世    さおとめ やすよ      九州大学    西   2
92  漆原 ありか   うるしばら ありか      九州大学    西  35

[92 rows x 5 columns]